#!/usr/bin/env bash

echo 'Updating the index.html file ...'
echo ''

# Update the index.html file
./bin/goTwig src index.html.twig > src/index.html

echo "Starting goStatic ..."
cd src
../bin/goStatic